### ISSUE TITLE
R/ must be flat

### ISSUE THREAD

**Issue by black-snow** [haganjam/FW_invert_biomass_allometry#3]
![grafik](https://user-images.githubusercontent.com/579733/215324715-488e1f51-6329-4076-97a4-c8ab3207a205.png)

For some reason `R/` must be flat. If you don't intend to include the code for building the database etc. in the final package we should move it to some other directory (and exclude that from rbuild).

I'd also recommend that you remove the absolute paths from the scripts and either keep them under the same project root. Are the data for building the DB huge? Or you pass the location as an argument to the corresponding scripts.  
I was thinking about building the DB in a pipeline (Actions) - but that would only be feasible if there isn't tons of data involved and it doesn't take forever to build it.

**Comment by haganjam** [comment]
I mean, the only thing that actually needs to be in the package is the search_database functions and the special_names_function. The rest can be managed externally because some of it is just to make figures for the paper and others is to create the database.

I think I would prefer to manage creating the database myself anyway so that I can check things etc. We could make a github actions to create the database but that still doesn't need to be within the package.

So right now, the raw data is stored on my local computer which I use to build the database that is uploaded to github. I think this is probably the best way of doing it. Another option would be for me to migrate the code to create the database and make figures etc. to a different repository and then just host the created database and search functions in a repository that can be submitted to CRAN (or vice versa): migrate the database and search functions to a separate repository.

What do you think?

**Comment by black-snow** [comment]
From an engineering view, it'd be ideal to have everything in the same place (+ the raw data). The creation the DB would be automatic and reproducible and automatic tests would verify that you've built the exact thing your code expects. If you have two separate repos it's easier for both to diverge.  
But that might not be feasible. The `database` is "too big" already as it is - cran wants packages <5 MB (with exceptions). I have yet to look up what they suggest - probably fetching the data on install time rather than on build time.

Maybe we should host the raw data somewhere (else). Dryad?

I think even having the code for the figures etc. within the same repo is fine if it's part of the publication. If I get it right, the *vignettes* are like little documentation snippets - they could as well include your figures.

---

Let me check what cran says about (binary) data.

**Comment by haganjam** [comment]
Okay, I see potential issues with things diverging... But, I suppose the tests could still be run in the repo itself on the database that was created externally. Maybe it's not ideal but it might be the most feasible.

Yes, my original idea was indeed to host the database externally on something like: https://knb.ecoinformatics.org/

Then, I build the database in some repo, upload directly to https://knb.ecoinformatics.org/ which allows different versions (unlike Dryad if I remember correctly). Then, the search code downloads the database directly into the R-environment when the package loads. This also means that people don't have to store the data locally on their computers.

Yes, the vignettes are kind of like a user-guide with some examples etc. That's true, I could use the analysis from the paper as part of the vignette.

**Comment by black-snow** [comment]
Sounds good to me.

I'll close this for now as it's resolved with the latest PR.
